language: generic
script:
- make ci

branches:
  only:
  - master

before_deploy:
- openssl aes-256-cbc -K $encrypted_5de9ee54225b_key -iv $encrypted_5de9ee54225b_iv -in deploy_key.enc -out deploy_key -d

deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key

notifications:
  email:
    on_success: never
    on_failure: always
