language: python
sudo: false
python:
  - "3.7"

install:
  - pip install bikeshed
  - bikeshed update

script: bikeshed --die-on=warning spec

before_deploy:
  - openssl aes-256-cbc -K $encrypted_5de9ee54225b_key -iv $encrypted_5de9ee54225b_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key

deploy:
  provider: script
  script: bash deploy.sh
  skip-cleanup: true
  on:
    branch: master
